# Generated by Django 5.2.15 on 2026-06-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("passed_count", models.PositiveIntegerField(default=0, verbose_name="通过文件数")),
                (
                    "missing_count",
                    models.PositiveIntegerField(default=0, verbose_name="缺失文件数"),
                ),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="失败文件数")),
                (
                    "overdue_missing_count",
                    models.PositiveIntegerField(default=0, verbose_name="逾期缺失文件数"),
                ),
                (
                    "overdue_failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="逾期失败文件数"),
                ),
                (
                    "remapped_count",
                    models.PositiveIntegerField(default=0, verbose_name="重映射文件数"),
                ),
                (
                    "shielded_count",
                    models.PositiveIntegerField(default=0, verbose_name="屏蔽文件数"),
                ),
                ("report_url", models.URLField(blank=True, default="", verbose_name="报告URL")),
                (
                    "scan_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="工程扫描时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="数据刷新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "扫描汇总",
                "verbose_name_plural": "扫描汇总",
            },
        ),
        migrations.CreateModel(
            name="MissingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_name", models.CharField(max_length=512, verbose_name="文件名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "缺失"),
                            ("failed", "失败"),
                            ("remapped", "重映射"),
                            ("shielded", "屏蔽"),
                        ],
                        max_length=16,
                        verbose_name="文件状态",
                    ),
                ),
                (
                    "sub_group",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="子分组"),
                ),
                (
                    "first_detected_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="首次发现时间"),
                ),
                ("is_overdue", models.BooleanField(default=False, verbose_name="是否逾期")),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missing_files",
                        to="dashboard.summary",
                        verbose_name="汇总",
                    ),
                ),
            ],
            options={
                "verbose_name": "缺失文件",
                "verbose_name_plural": "缺失文件",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("search_version", models.CharField(max_length=16, verbose_name="扫描版本")),
                ("product", models.CharField(max_length=32, verbose_name="产品")),
                ("group_name", models.CharField(max_length=64, verbose_name="组件组名")),
                ("lan", models.CharField(max_length=32, verbose_name="编程语言")),
                ("source_type", models.CharField(max_length=32, verbose_name="源码类型")),
                ("data_type", models.CharField(max_length=32, verbose_name="数据类型")),
                ("tool_name", models.CharField(max_length=64, verbose_name="工具名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "扫描任务",
                "verbose_name_plural": "扫描任务",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "search_version",
                            "product",
                            "group_name",
                            "lan",
                            "source_type",
                            "data_type",
                            "tool_name",
                        ),
                        name="uniq_task_dimensions",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="summary",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.task",
                verbose_name="任务",
            ),
        ),
    ]
